---
title: "Testing Betweenness Centrality on Toy Graphs"
format: html
---

```{python}
import sys
sys.path.insert(0, 'spatial-centrality-pub/algo')
import centrality as sbc
import net_helper as nh
import pandas as pd
import geopandas as gpd
import time

from matplotlib.pyplot import plot
import os
import numpy as np
import networkx as nx
import osmnx as ox
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon as MplPolygon
from matplotlib.colors import TwoSlopeNorm
import momepy as mp

from superblockify.metrics.measures import betweenness_centrality as sb_betweenness_centrality
from superblockify.metrics.distances import calculate_path_distance_matrix as sb_calculate_path_distance_matrix
from superblockify.population.approximation import add_edge_population as sb_add_edge_population

```

Defining the cities and some parameters for extracting the real networks.

```{python}
# City coordinates and buffer
cities = [
    {"name": "Lima", "lat": -12.077948042115647, "lon": -77.05096688507561},
    {"name": "Brussels", "lat": 50.856117793777145, "lon": 4.381718424984715},
    # {"name": "Rome", "lat": 41.89900799198937, "lon": 12.512797548177907},
    {"name": "Cairo", "lat": 30.036716997454857, "lon": 31.23947439245143},
    {"name": "Salt Lake City", "lat": 40.75984495218752, "lon": -111.88769690322184},
    {"name": "Bogota", "lat": 4.646242884611647, "lon": -74.08436455625211},
    {"name": "Leeds", "lat": 53.81303429075668,  "lon": -1.508881353201933},
    {"name": "Milton Keynes", "lat": 52.0367171540023, "lon": -0.7324001661371712},
    {"name": "Lisbon", "lat": 38.72778849555562, "lon": -9.162267565552924},
    {"name": "New York", "lat": 40.7589664816669, "lon": -73.96121069380527},
    {"name": "Brasilia", "lat": -15.76133509896713, "lon": -47.88377302616466},
    {"name": "Sao Paulo", "lat": -23.54468352821393, "lon": -46.67047368527096},

]

BUFFER_M = 2500 
NETWORK_TYPE = "drive"
UNIT = "time"
```


Defining a function to compute node weights based on the areas of the tessellation cells associated with each edge. The weight for each node is calculated as the sum of half the area of the tessellation cells for edges that are connected to that node (both incoming and outgoing).

```{python}
def compute_node_weights(edges_df, tessellation_df):
    # Join edges with tessellation areas
    tmp = edges_df[['u', 'v', 'geometry']].copy()
    tmp['area'] = tessellation_df.geometry.area
    
    # Split edge weight to end nodes
    wa = tmp.groupby('u')[['area']].sum() / 2
    wa.index.name = 'node_id'
    wb = tmp.groupby('v')[['area']].sum() / 2
    wb.index.name = 'node_id'
    
    # Combine weights for each node
    w = wa.join(wb, lsuffix='_from', rsuffix='_to', how='outer')
    w.fillna(0, inplace=True)
    w['weight'] = w['area_from'] + w['area_to']
    
    return w
```

```{python}
def compute_node_pop(edges_df, weight_col_name='population'):
    # Reset index to make 'u' and 'v' regular columns
    edges_reset = edges_df.reset_index()
    
    # Join edges with tessellation areas
    tmp = edges_reset[['u', 'v', weight_col_name]].copy()
    
    # Split edge weight to end nodes
    wa = tmp.groupby('u')[[weight_col_name]].sum() / 2
    wa.index.name = 'node_id'
    wb = tmp.groupby('v')[[weight_col_name]].sum() / 2
    wb.index.name = 'node_id'
    
    # Combine weights for each node
    w = wa.join(wb, lsuffix='_from', rsuffix='_to', how='outer')
    w.fillna(0, inplace=True)
    w['weight'] = w[f'{weight_col_name}_from'] + w[f'{weight_col_name}_to']
    
    return w
```

A for loop to iterate over real network extracts and compute different versions of the betweenness centrality:

- Standard betweenness centrality using NetworkX's implementation.
- Spatial betweenness centrality using the custom implementation as defined in the `spatial-centrality-pub` repository by Christian Werner (taken from https://github.com/christian-werner/spatial-centrality-pub).
- Simplified betweenness centrality using the `superblockify` library, which assumes a single shortest path between node pairs.
- Length scaled betweenness centrality using the same algorithm as the simplified version but appliying a scaling factor based on the lenght of the shortest path. 



```{python}
for city_info in cities:
    # city_info = cities[0]
    city_name = city_info["name"]
    graph_file = f"graphs/small/{city_name}.graphml"
    if not os.path.exists(graph_file):
         graph = ox.graph_from_point((city_info["lat"], city_info["lon"]),
         dist= BUFFER_M,
         network_type=NETWORK_TYPE,
         simplify=True,
         custom_filter=None)
         ox.save_graphml(graph, graph_file)
    else:
        graph = ox.load_graphml(graph_file)
    
    graph = ox.add_edge_speeds(graph)
    graph = ox.add_edge_travel_times(graph)
    graph = ox.project_graph(graph)
    sb_add_edge_population(graph, overwrite=True)

    graph_undirected = graph.to_undirected()
    nodes_gdf, edges_filtered = ox.graph_to_gdfs(graph_undirected)
    nodes_gdf, edges_gdf = ox.graph_to_gdfs(graph)
    edges_filtered = edges_filtered.reset_index()

    
    
    processed_net_file = f"graphs/small/{city_name}.gpkg"

    if not os.path.exists(processed_net_file):
        nodes_proj = nodes_gdf.to_crs(nodes_gdf.estimate_utm_crs())
        edges_proj = edges_filtered.to_crs(nodes_proj.crs)

        envelope = nodes_proj.union_all().convex_hull    
        buffer = envelope.buffer(0.05*(envelope.area/np.pi)**0.5) # Buffering 5% of the equivalent radius of the hull
        
        # Time the following blocks of code to see how long they take to run

        start_time = time.time()
        tessellation_nodes = mp.morphological_tessellation(nodes_proj, clip= buffer)
        tessellation_nodes.index = nodes_proj.index
        tessellation_nodes['weight'] = tessellation_nodes.geometry.area
        
        end_time = time.time()
        print(f"Tessellation nodes computation time: {end_time - start_time} seconds for {city_name}")


        
        node_weights_pop = compute_node_pop(edges_gdf)
              



        c_standard = nx.edge_betweenness_centrality(graph, normalized=True, weight='travel_time')
        c_spatial = sbc.spatial_betweenness_centrality(graph, tessellation_nodes, tessellation_nodes, normalized=True, weight='travel_time')
        # c_spatial = sbc.spatial_betweenness_centrality(graph, tessellation_edges, tessellation_edges, normalized=True, weight='travel_time')
        c_pop = sbc.spatial_betweenness_centrality(graph, node_weights_pop, node_weights_pop, normalized=True, weight='travel_time')

        node_order = list(graph.nodes)
        matrix, predecessors = sb_calculate_path_distance_matrix(graph, weight = "travel_time", node_order = node_order)
        sb_betweenness_centrality(graph, node_order, matrix, predecessors, weight="travel_time")

        # save the bc results in a file and load it if it already exists to avoid recomputation



        tdf = pd.DataFrame({
        'u': [u for u, v, k in graph.edges(keys=True)],
        'v': [v for u, v, k in graph.edges(keys=True)],
        'key': [k for u, v, k in graph.edges(keys=True)],
        'edge_betweenness_normal': [data.get('edge_betweenness_normal', 0) for u, v, k, data in graph.edges(keys=True, data=True)],
        'edge_betweenness_length': [data.get('edge_betweenness_length', 0) for u, v, k, data in graph.edges(keys=True, data=True)],
        'edge_betweenness_linear': [data.get('edge_betweenness_linear', 0) for u, v, k, data in graph.edges(keys=True, data=True)],
        'c_standard': [c_standard.get((u, v, k), 0) for u, v, k in graph.edges(keys=True)],
        'c_spatial': [c_spatial.get((u, v, k), 0) for u, v, k in graph.edges(keys=True)],
        'c_pop': [c_pop.get((u, v, k), 0) for u, v, k in graph.edges(keys=True)]
        })



        edges_with_centrality = edges_proj.merge(
        tdf, 
        on=['u', 'v', 'key'], 
        how='left'
        )

        edges_with_centrality.to_file(processed_net_file, layer='edges', driver='GPKG')
        tessellation_nodes.to_file(processed_net_file, layer='tessellation', driver='GPKG')
```

A loop for producing the visual comparisons

```{python}
for city_info in cities:
    city_name = city_info["name"]
    processed_net_file = f"graphs/small/{city_name}.gpkg"

    edges_with_centrality = gpd.read_file(processed_net_file, layer='edges')
    tessellation_nodes = gpd.read_file(processed_net_file, layer='tessellation')

    # Create a directory to save the plots if it doesn't exist
    if not os.path.exists('plots_cities'):
        os.makedirs('plots_cities')
    
    # Fill any NaN values with 0
    edges_with_centrality['c_standard'] = edges_with_centrality['c_standard'].fillna(0)
    edges_with_centrality['c_spatial'] = edges_with_centrality['c_spatial'].fillna(0)
    edges_with_centrality['c_pop'] = edges_with_centrality['c_pop'].fillna(0)
    edges_with_centrality['edge_betweenness_normal'] = edges_with_centrality['edge_betweenness_normal'].fillna(0)
    edges_with_centrality['edge_betweenness_length'] = edges_with_centrality['edge_betweenness_length'].fillna(0)

    # An arrangement of 6 plots 2 x 3, the top row with the standard, spatial and population BC plots of the graph, and the bottom row with the scatter plot comparing the three measures and maps with the spatial - standard BC and pop - standard BC ratios.

    fig, axs = plt.subplots(2, 3, figsize=(30, 14))


    # Get common color scale for both BC plots
    vmin = min(edges_with_centrality['c_standard'].min(), edges_with_centrality['c_spatial'].min())
    vmax = max(edges_with_centrality['c_standard'].max(), edges_with_centrality['c_spatial'].max())
    vmin_pop = min(edges_with_centrality['c_standard'].min(), edges_with_centrality['c_pop'].min())
    vmax_pop = max(edges_with_centrality['c_standard'].max(), edges_with_centrality['c_pop'].max())

    edges_with_centrality.plot(column='c_standard', ax=axs[0, 0], legend=True, cmap='viridis', vmin=vmin, vmax=vmax)
    axs[0, 0].set_title('Standard Betweenness Centrality')
    axs[0, 0].axis('off')
    edges_with_centrality.plot(column='c_spatial', ax=axs[0, 1], legend=True, cmap='viridis', vmin=vmin, vmax=vmax)
    axs[0, 1].set_title('Spatial Betweenness Centrality')
    axs[0, 1].axis('off')
    edges_with_centrality.plot(column='c_pop', ax=axs[0, 2], legend=True, cmap='viridis', vmin=vmin_pop, vmax=vmax_pop)
    axs[0, 2].set_title('Population Betweenness Centrality')
    axs[0, 2].axis('off')

    axs[1, 0].scatter(list(edges_with_centrality['c_standard']), list(edges_with_centrality['c_spatial']), alpha=0.5, color='purple')
    axs[1, 0].scatter(list(edges_with_centrality['c_standard']), list(edges_with_centrality['c_pop']), alpha=0.5, color='orange')
    axs[1, 0].axis('equal')
    axs[1, 0].set_xlabel('Standard Betweenness Centrality')
    axs[1, 0].set_ylabel('Weighted Betweenness Centrality')
    axs[1, 0].set_title('Comparison of Standard BC vs Weighted BC')
    # legend for the scatter plot
    axs[1, 0].legend(['Spatial BC', 'Population BC'])
    axs[1, 0].grid(True)
    edges_with_centrality['c_diff'] = edges_with_centrality['c_spatial'] - edges_with_centrality['c_standard']
    edges_with_centrality['c_ratio'] = np.log(edges_with_centrality['c_spatial']) - np.log(edges_with_centrality['c_standard'])
    edges_with_centrality['c_ratio'] = edges_with_centrality['c_ratio'].fillna(0)
    
    edges_with_centrality['c_diff_pop'] = edges_with_centrality['c_pop'] - edges_with_centrality['c_standard']
    edges_with_centrality['c_ratio_pop'] = np.log(edges_with_centrality['c_pop']) - np.log(edges_with_centrality['c_standard'])
    edges_with_centrality['c_ratio_pop'] = edges_with_centrality['c_ratio_pop'].fillna(0)
    
    # Plot tessellation with alpha based on area
    areas = tessellation_nodes.geometry.area
    areas_normalized = (areas - areas.min()) / (areas.max() - areas.min())

    for idx, row in tessellation_nodes.iterrows():
        if row.geometry.geom_type == 'Polygon':
            x, y = row.geometry.exterior.xy
            alpha = 0.2 + 0.6 * areas_normalized[idx]
            poly = MplPolygon(list(zip(x, y)), alpha=alpha, facecolor='gray', edgecolor='white', linewidth=0.1)
            axs[1, 1].add_patch(poly)

    # Plot edges with difference centrality
    
    norm = TwoSlopeNorm(vcenter=0)
    edges_with_centrality.plot(column='c_ratio', ax=axs[1, 1], legend=True, cmap='coolwarm', norm=norm)
    axs[1, 1].set_title('Log Ratio (Spatial BC/Standard BC)')
    axs[1, 1].axis('off')

    edges_with_centrality.plot(column='c_ratio_pop', ax=axs[1, 2], legend=True, cmap='coolwarm', norm=norm)
    axs[1, 2].set_title('Log Ratio (Population BC/Standard BC)')
    axs[1, 2].axis('off')
    fig.suptitle(f'City: {city_name}', fontsize=16, fontweight='bold')
    plt.tight_layout()

    # Save the plot as PNG
    filename = f"plots_cities/{city_name}_bc_comparison.png"
    fig.savefig(filename, dpi=330)
    plt.close(fig)

    fig, axs = plt.subplots(2, 2, figsize=(12, 12))
    
    # Get common color scale for both BC plots
    vmin = 0
    vmax = max(edges_with_centrality['c_standard'].max(),edges_with_centrality['edge_betweenness_normal'].max(), edges_with_centrality['edge_betweenness_length'].max())
    edges_with_centrality.plot(column='edge_betweenness_normal', ax=axs[0, 0], legend=True, cmap='viridis', vmin=vmin, vmax=vmax)
    axs[0, 0].set_title('SB Standard Betweenness Centrality')
    edges_with_centrality.plot(column='edge_betweenness_length', ax=axs[0, 1], legend=True, cmap='viridis', vmin=vmin, vmax=vmax)
    axs[0, 1].set_title('SB Length Betweenness Centrality')
    axs[1, 0].scatter(list(edges_with_centrality['c_standard']), list(edges_with_centrality['edge_betweenness_normal']), alpha=0.5, color='blue', label='edge_betweenness_normal')
    axs[1, 0].scatter(list(edges_with_centrality['c_standard']), list(edges_with_centrality['edge_betweenness_length']), alpha=0.5, color='orange', label='edge_betweenness_length')
    axs[1, 0].axis('equal')
    axs[1, 0].set_xlabel('Standard Betweenness Centrality')
    axs[1, 0].set_ylabel('SB Edge Betweenness Centrality Variants')
    axs[1, 0].set_title('Comparison of Standard BC vs SB Calculation')
    edges_with_centrality.plot(column='c_standard', ax=axs[1, 1], legend=True, cmap='viridis', vmin=vmin, vmax=vmax)
    axs[1, 1].set_title('Standard Betweenness Centrality')

    filename = f"plots_cities/{city_name}_bc_comparison_sb.png"
    fig.savefig(filename, dpi=330, bbox_inches='tight')
    plt.close(fig)
    
```

Subsetting the sparse networks to the top 20% of the edges

```{python}
for city_info in cities:
    city_name = city_info["name"]
    processed_net_file = f"graphs/small/{city_name}.gpkg"


    edges_with_centrality = gpd.read_file(processed_net_file, layer='edges')
    tessellation_nodes = gpd.read_file(processed_net_file, layer='tessellation')

    # Create a directory to save the plots if it doesn't exist
    if not os.path.exists('plots_sparse_cities'):
        os.makedirs('plots_sparse_cities')
    
    # Fill any NaN values with 0
    edges_with_centrality['c_standard'] = edges_with_centrality['c_standard'].fillna(0)
    edges_with_centrality['c_spatial'] = edges_with_centrality['c_spatial'].fillna(0)
    edges_with_centrality['edge_betweenness_normal'] = edges_with_centrality['edge_betweenness_normal'].fillna(0)
    edges_with_centrality['edge_betweenness_length'] = edges_with_centrality['edge_betweenness_length'].fillna(0)

    edges_with_centrality['top_20_standard'] = edges_with_centrality['c_standard'] >= edges_with_centrality['c_standard'].quantile(0.8)
    edges_with_centrality['top_20_spatial'] = edges_with_centrality['c_spatial'] >= edges_with_centrality['c_spatial'].quantile(0.8)
    edges_with_centrality['top_20_sb_normal'] = edges_with_centrality['edge_betweenness_normal'] >= edges_with_centrality['edge_betweenness_normal'].quantile(0.8)
    edges_with_centrality['top_20_sb_length'] = edges_with_centrality['edge_betweenness_length'] >= edges_with_centrality['edge_betweenness_length'].quantile(0.8)

    edges_with_centrality['category'] = 'None'
    edges_with_centrality.loc[edges_with_centrality['top_20_standard'] & ~edges_with_centrality['top_20_spatial'], 'category'] = 'Standard Only'
    edges_with_centrality.loc[~edges_with_centrality['top_20_standard'] & edges_with_centrality['top_20_spatial'], 'category'] = 'Spatial Only'
    edges_with_centrality.loc[edges_with_centrality['top_20_standard'] & edges_with_centrality['top_20_spatial'], 'category'] = 'Both'

    edges_with_centrality['thickness'] = 0.5
    edges_with_centrality.loc[edges_with_centrality['category'] != 'None', 'thickness'] = 2

    fig, axes = plt.subplots(1, 2, figsize=(30, 10))
    edges_with_centrality.plot(color=edges_with_centrality['category'].map(colors), legend=True, linewidth=edges_with_centrality['thickness'], ax=axes[0])
    axes[0].set_title(f'Edge Categories by Betweenness Centrality - {city_name}')
    axes[0].axis('off')
    for category, color in colors.items():
        subset = edges_with_centrality[edges_with_centrality['category'] == category]
        axes[1].scatter(subset['c_standard'], subset['c_spatial'], alpha=0.3, color=color, label=category)
    axes[1].set_xlabel('Standard Betweenness Centrality')
    axes[1].set_ylabel('Spatial Betweenness Centrality')
    axes[1].set_title('Top 20% Edges by Betweenness Centrality')
    axes[1].set_xscale('log')
    axes[1].set_yscale('log')
    axes[1].legend()
    plt.tight_layout()
    filename = f"plots_sparse_cities/{city_name}_bc_comparison_top20.png"
    plt.savefig(filename, dpi=330, bbox_inches='tight')
    
```

